
CREATE TABLE `assault_rifles` (
  `ID` int(11) NOT NULL,
  `marca` text DEFAULT NULL,
  `modello` text DEFAULT NULL,
  `stato` text DEFAULT NULL,
  `titolo` text DEFAULT NULL,
  `maintext` text DEFAULT NULL,
  `secondarytext` text DEFAULT NULL,
  `summary` text DEFAULT NULL,
  `sub1` text DEFAULT NULL,
  `sub2` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;



INSERT INTO `assault_rifles` (`ID`, `marca`, `modello`, `stato`, `titolo`, `maintext`, `secondarytext`, `summary`, `sub1`, `sub2`) VALUES
(1, 'AK', '74', 'Russia', 'Ak 74', 'L\'AK-74 è un fucile d\'assalto originario dell\'Unione Sovietica, sviluppato negli anni \'70 come successore dell\'AK-47. Progettato da Mikhail Kalashnikov, il noto ingegnere russo, l\'AK-74 è famoso per la sua affidabilità, robustezza e semplicità di costruzione, caratteristiche che erano già presenti nel predecessore.\r\n\r\nIl fucile è alimentato da un caricatore rimovibile con capacità standard di 30 colpi, sparando il proiettile 5,45x39mm, ideato per migliorare la precisione e la gittata rispetto al calibro 7,62x39mm dell\'AK-47. La canna dell\'AK-74 è lunga e filettata per l\'installazione di accessori o dispositivi di soppressione del rinculo. Il design ergonomico della carabina presenta un calcio pieghevole o telescopico, consentendo la personalizzazione per adattarsi alle esigenze operative.\r\n\r\nLa selettore di fuoco dell\'AK-74 offre modalità di sparo automatico e semiautomatico, garantendo flessibilità d\'uso in varie situazioni. La fama dell\'AK-74 deriva anche dalla sua resistenza alle condizioni avverse, in grado di funzionare in ambienti estremi come il freddo artico o l\'ardente calura deserta.', 'L\'AK-74 è diventato uno dei fucili d\'assalto più diffusi a livello globale, utilizzato da numerose forze armate e gruppi paramilitari. La sua presenza è stata particolarmente significativa durante la Guerra Fredda e in molte conflittualità regionali. La sua economia di produzione e la facilità di manutenzione lo rendono un\'arma preferita in molte aree del mondo.\r\n\r\nLa cartuccia 5,45x39mm, introdotta con l\'AK-74, ha dimostrato un bilanciamento efficace tra potenza di fuoco, precisione e gestione del rinculo. L\'AK-74 è stato adottato da varie nazioni oltre alla Russia, tra cui molti stati dell\'ex blocco sovietico e dell\'Europa orientale.\r\n\r\nNonostante la sua origine militare, l\'AK-74 ha anche influenzato il mondo civile, con molte varianti commerciali disponibili per gli appassionati di armi da fuoco. La sua presenza continua a suscitare dibattiti su questioni di sicurezza, controllo delle armi e geopolitica.', NULL, 'Caratteristiche dell\'Ak 74', 'Impatto e Utilizzo dell\'AK-74'),
(2, 'M', '16', 'USA', 'M16', 'L\'M16 è un fucile d\'assalto statunitense sviluppato negli anni \'60. Progettato da Eugene Stoner, l\'M16 è noto per la sua precisione, leggerezza e modularità. Inizialmente adottato dalle forze armate degli Stati Uniti durante la Guerra del Vietnam, l\'M16 è diventato uno degli armamenti più riconoscibili e utilizzati a livello globale.\r\n\r\nIl fucile utilizza un caricatore rimovibile, generalmente con capacità di 20 o 30 colpi, e spara il proiettile 5,56x45mm NATO. La canna è spesso dotata di un freno di bocca e un sistema di aggancio per appendere accessori come lanciagranate o baionette. Il calcio, spesso telescopico, è progettato ergonomicamente per migliorare la maneggevolezza.\r\n\r\nL\'M16 è caratterizzato da una selettore di fuoco che offre modalità di sparo semiautomatico e automatico. La sua progettazione accurata e la lunga gittata del proiettile lo rendono efficace sia in combattimento ravvicinato che in situazioni di tiro di precisione.', 'L\'M16 ha avuto un impatto significativo nella storia militare contemporanea, in particolare durante la Guerra del Vietnam. Tuttavia, ha suscitato dibattiti sulla sua affidabilità in ambienti polverosi e fangosi. Successivamente, l\'M16 è stato sottoposto a miglioramenti e varianti, con l\'M4 Carbine che è diventato popolare tra le forze armate degli Stati Uniti.\r\n\r\nL\'arma è stata adottata da numerose nazioni alleate degli Stati Uniti e è diventata uno degli standard NATO. La cartuccia 5,56x45mm è stata progettata per ridurre il peso del munizionamento portato dal soldato, permettendo loro di trasportare più munizioni. L\'M16 ha anche trovato applicazioni civili, con versioni semiautomatiche disponibili per i civili appassionati di armi da fuoco.\r\n\r\nNonostante la sua popolarità, l\'M16 è stato oggetto di discussioni riguardo alle politiche sul controllo delle armi e alle controversie sull\'uso militare. La sua storia e evoluzione continuano a influenzare il mondo delle armi da fuoco e le strategie di difesa a livello globale.', NULL, 'Caratteristiche dell\'M16', 'Impatto e Utilizzo dell\'M16'),
(3, 'Steyr', 'AUG', 'Australia', 'Steyr AUG', 'Lo Steyr AUG, sviluppato dall\'azienda austriaca Steyr Mannlicher negli anni \'70, rappresenta una pietra miliare nell\'evoluzione dei fucili d\'assalto. Questo bullpup, con la sua configurazione innovativa, ha introdotto concetti avanzati di design. La sua peculiarità risiede nella disposizione compatta grazie al sistema bullpup, che consente una canna più lunga all\'interno di un fucile più corto, migliorando la precisione e la manovrabilità.\r\n\r\nEquipaggiato con un caricatore trasparente, lo Steyr AUG utilizza la cartuccia 5,56x45mm NATO, garantendo una potenza di fuoco adeguata in vari contesti operativi. Il calcio integrato nella carcassa contribuisce a una migliore ergonomia, mentre il selettore di fuoco offre modalità semiautomatica, automatica e raffica. La versatilità e l\'avanzato sistema modulare hanno reso lo Steyr AUG un\'arma adottata da numerose forze armate in tutto il mondo.', 'Lo Steyr AUG ha lasciato un\'impronta significativa nell\'ambito delle armi da fuoco, dimostrando la sua efficacia in una varietà di scenari operativi. La sua adozione da parte di diverse forze armate, oltre ai reparti speciali, è testimone della sua versatilità e affidabilità. Durante la Guerra Fredda, lo Steyr AUG ha rappresentato uno strumento moderno e avanzato, e la sua influenza è perdurata nel tempo.\r\n\r\nOltre al suo impiego militare, varianti civili dello Steyr AUG sono ricercate nel mercato degli appassionati di armi da fuoco per la loro innovazione e design unico. La sua storia continua a contribuire alla narrativa delle armi da fuoco, evidenziando il ruolo cruciale che quest\'arma ha svolto nel contesto delle forze armate e nella cultura delle armi.', NULL, 'Caratteristiche dello Steyr AUG', 'Impatto e Utilizzo dello Steyr AUG'),
(4, 'FN', 'FAL', 'Belgio', 'FN FAL', 'Il FN FAL, progettato dall\'azienda belga Fabrique Nationale (FN) durante gli anni \'50, è un fucile d\'assalto iconico che ha lasciato un\'impronta duratura nella storia delle armi da fuoco. Concepito come un\'arma robusta e affidabile, il FN FAL spara il potente proiettile 7,62x51mm NATO. Il suo design tradizionale è caratterizzato dalla configurazione standard del calcio, della canna e del caricatore rimovibile.\r\n\r\nIl FN FAL è stato adottato da numerose forze armate in tutto il mondo, guadagnando una reputazione per la sua precisione e la potenza di fuoco. Il calcio pieghevole o fissato può essere personalizzato per adattarsi alle preferenze dell\'utilizzatore. La presenza di un selettore di fuoco consente l\'uso in modalità semiautomatica o automatica, garantendo flessibilità operativa.', 'Il FN FAL ha svolto un ruolo cruciale durante la Guerra Fredda e oltre, essendo ampiamente utilizzato in conflitti regionali. La sua adozione da parte di molte nazioni, sia della NATO che al di fuori di essa, testimonia la sua versatilità e affidabilità. Il proiettile 7,62mm NATO fornisce una notevole penetrazione e gittata, rendendo il FN FAL adatto a una varietà di scenari operativi.\r\n\r\nOltre al suo impiego militare, il FN FAL è stato apprezzato dai collezionisti e dagli appassionati di armi da fuoco. Il suo design classico continua a influenzare il mondo delle armi da fuoco, dimostrando come l\'equilibrio tra potenza, precisione e praticità possa rendere un\'arma un punto di riferimento nella storia delle armi d\'assalto.', NULL, 'Caratteristiche del FN FAL', 'Impatto e Utilizzo del FN FAL'),
(5, 'Heckler & Koch', 'G36', 'Germania', 'Heckler & Koch G36', 'Il fucile d\'assalto G36, prodotto dalla rinomata Heckler & Koch tedesca, è una pietra miliare dell\'ingegneria delle armi moderne. Introdotta negli anni \'90, questa arma si distingue per il suo design modulare e l\'impiego di materiali leggeri. Sparando il proiettile 5,56x45mm NATO, il G36 offre una combinazione di precisione e manovrabilità.\r\n\r\nIl calcio telescopico e il sistema modulare permettono una personalizzazione avanzata, adattando l\'arma alle esigenze operative. La canna integrata con sistema di raffreddamento offre un\'efficienza termica superiore. Il G36 è dotato di un selettore di fuoco con modalità semiautomatica, automatica e raffica, garantendo una flessibilità d\'uso in vari contesti.', 'Il G36 ha ottenuto un\'ampia adozione in molte forze armate e forze di sicurezza in tutto il mondo, grazie alla sua affidabilità e alle caratteristiche avanzate. Utilizzato in missioni operative e pattugliamenti, il G36 ha dimostrato di essere una risorsa versatile. La sua ergonomia e il basso peso lo rendono adatto a situazioni di combattimento e movimento.\r\n\r\nOltre al servizio militare, il G36 è stato apprezzato per le sue performance nel mercato civile. La sua reputazione di precisione e affidabilità ha reso questo fucile un\'icona nel panorama delle armi da fuoco. La continua presenza del G36 in vari contesti sottolinea la sua importanza nella storia delle armi d\'assalto contemporanee.', NULL, 'Caratteristiche del G36', 'Impatto e Utilizzo del G36 ');



CREATE TABLE `assault_smg` (
  `ID` int(11) NOT NULL,
  `marca` text DEFAULT NULL,
  `modello` text DEFAULT NULL,
  `stato` text DEFAULT NULL,
  `titolo` text DEFAULT NULL,
  `maintext` text DEFAULT NULL,
  `secondarytext` text DEFAULT NULL,
  `summary` text DEFAULT NULL,
  `sub1` text DEFAULT NULL,
  `sub2` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


INSERT INTO `assault_smg` (`ID`, `marca`, `modello`, `stato`, `titolo`, `maintext`, `secondarytext`, `summary`, `sub1`, `sub2`) VALUES
(1, 'Heckler & Koch', 'MP5', 'Germania', 'Heckler & Koch MP5', 'L\'MP5, prodotto dalla rinomata Heckler & Koch tedesca, è un mito nell\'ambito delle submachine gun, entrato in servizio negli anni \'60. Dotato di una costruzione compatta e di precisione, l\'MP5 è alimentato dal proiettile 9x19mm Parabellum. Quest\'arma è ampiamente riconosciuta per la sua affidabilità, precisione e versatilità.\r\n\r\nIl design dell\'MP5 presenta una configurazione bullpup, con una canna corta all\'interno di un fucile compatto, offrendo un equilibrio ideale tra potenza di fuoco e manovrabilità. Il calcio pieghevole contribuisce alla sua portabilità e alla sua adattabilità in spazi ristretti. L\'MP5 è spesso equipaggiato con accessori come mirini ottici e impugnature verticali per una maggiore ergonomia.', 'L\'MP5 ha ottenuto un riconoscimento globale ed è stato adottato da numerose forze di sicurezza e unità speciali in tutto il mondo. La sua efficacia in situazioni di combattimento ravvicinato e in operazioni speciali lo ha reso uno strumento di fiducia per professionisti delle forze dell\'ordine e militari. La sua presenza è stata rilevante anche in scenari civili, come strumento di difesa personale e nel mondo degli sport di tiro.\r\n\r\nL\'eredità dell\'MP5 persiste nel panorama delle armi da fuoco, confermando il suo status di classico e il suo impatto duraturo. La combinazione di prestazioni affidabili e design innovativo ha fatto dell\'MP5 un\'icona delle submachine gun, continuando a influenzare il mercato delle armi da fuoco e la cultura delle forze di sicurezza.', NULL, 'Caratteristiche dell\'MP5', 'Impatto e Utilizzo dell\'MP5'),
(2, 'FN', 'P90', 'Belgio', 'FN P90', 'Il FN P90, sviluppato dalla Fabrique Nationale Herstal (FN) del Belgio negli anni \'90, è un\'arma unica e distintiva nel panorama delle Personal Defense Weapons (PDW). Utilizza il proiettile 5,7x28mm, progettato per offrire un compromesso tra il potente calibro delle pistole e la gittata dei fucili d\'assalto. Il design futuristico e compatto dell\'arma è evidente con la disposizione bullpup e il caricatore situato sulla parte superiore.\r\n\r\nLa conformazione del P90 lo rende particolarmente adatto a situazioni di combattimento ravvicinato, mentre il sistema di mira integrato e il calcio ergonomico contribuiscono alla precisione in tiro. La versatilità dell\'arma è ulteriormente ampliata dalla sua impugnatura ergonomica e dal selettore di fuoco che offre modalità semiautomatica e automatica.', 'Il FN P90 ha guadagnato popolarità nelle forze di sicurezza e tra le unità speciali grazie alla sua straordinaria maneggevolezza e alle caratteristiche balistiche del proiettile 5,7mm. L\'arma è stata adottata in vari contesti, inclusi reparti di polizia e forze armate, dove la sua configurazione compatta si rivela preziosa in ambienti confinati. La sua leggerezza e il design innovativo lo rendono un\'opzione attraente anche per situazioni di difesa personale.\r\n\r\nOltre al suo utilizzo tattico-militare, il FN P90 è stato impiegato anche nell\'ambito civile, ad esempio nella sicurezza privata e tra appassionati di armi da fuoco. Il design inconfondibile e le sue caratteristiche tecniche avanzate consolidano il P90 come un\'icona nel panorama delle armi da fuoco contemporanee.', NULL, 'Caratteristiche del FN P90', 'Impatto e Utilizzo del FN P90'),
(3, 'IMI', 'Uzi', 'Israele', 'IMI UZI', 'La IMI UZI, originariamente sviluppata in Israele negli anni \'50, è una submachine gun leggendaria e iconica nel mondo delle armi da fuoco. Caratterizzata da un design compatto e riconoscibile, l\'UZI utilizza il proiettile 9x19mm Parabellum, offrendo un bilanciamento tra potenza di fuoco e maneggevolezza. Il caricatore a scatola, posizionato nella parte superiore dell\'arma, è un tratto distintivo del suo design.\r\n\r\nCon una canna corta e un calcio pieghevole, l\'UZI è pensato per la massima portabilità e facilità d\'uso in spazi ristretti. Il selettore di fuoco permette modalità semiautomatica e automatica, rendendola efficace sia in situazioni di difesa personale che in combattimenti ravvicinati.', 'L\'UZI ha guadagnato una vasta adozione nelle forze armate, nei reparti di polizia e tra le unità speciali in tutto il mondo grazie alla sua affidabilità e alle dimensioni compatte. La sua presenza è stata significativa in conflitti internazionali e operazioni speciali. Nonostante la sua introduzione iniziale per scopi militari, l\'UZI è diventato popolare anche nel settore civile, apprezzato per la sua semplicità d\'uso e design riconoscibile.\r\n\r\nLa IMI UZI è un simbolo della versatilità delle submachine gun e della loro capacità di adattarsi a una varietà di scenari operativi. Il suo status di classico e la sua eredità continuano a renderla una delle armi da fuoco più iconiche del ventesimo secolo.', NULL, 'Caratteristiche della IMI UZI', 'Impatto e Utilizzo della IMI UZI'),
(4, 'Kalashnikov', 'PP-19 Bizon', 'Russia', 'Kalashnikov PP-19 Bizon', 'La Kalashnikov PP-19 Bizon, sviluppata in Russia alla fine degli anni \'90, rappresenta una submachine gun unica e specializzata. Progettata per impiegare il proiettile 9x18mm Makarov o il 9x19mm Parabellum, la PP-19 Bizon si distingue per il suo design bullpup e per il caricatore a tamburo, caratteristiche insolite per una submachine gun.\r\n\r\nIl caricatore a tamburo da 64 colpi è posizionato sopra la canna, contribuendo a una distribuzione equilibrata del peso e permettendo una maggiore capacità di fuoco. Il design compatto e l\'impugnatura ergonomica rendono la PP-19 adatta per operazioni di combattimento ravvicinato. Il selettore di fuoco offre modalità semiautomatica e automatica, garantendo flessibilità in vari scenari operativi.', 'La PP-19 Bizon è stata impiegata in diverse forze di sicurezza russe e in molte situazioni operative, specialmente in contesti urbani o di sicurezza interna. La sua configurazione bullpup e il caricatore a tamburo la rendono adatta a spazi ristretti e a situazioni di combattimento ravvicinato. La presenza della PP-19 Bizon si è estesa anche a operatori di sicurezza privata e, in misura limitata, al mercato civile, dove la sua originalità e l\'efficienza operativa hanno suscitato interesse tra gli appassionati di armi da fuoco. La PP-19 Bizon, con la sua peculiare estetica e le prestazioni distintive, continua a occupare uno spazio unico nel panorama delle submachine gun contemporanee.', NULL, 'Caratteristiche della PP-19 Bizon', 'Impatto e Utilizzo della Kalashnikov PP-19 Bizon'),
(5, 'Steyr', 'TMP', 'Austria', 'Steyr TMP', 'La Steyr TMP (Tactical Machine Pistol), sviluppata dall\'austriaca Steyr Mannlicher alla fine degli anni \'90, è una submachine gun compatta e avanzata. Progettata per la massima maneggevolezza, la TMP utilizza il proiettile 9x19mm Parabellum. Il suo design ultramoderno presenta un caricatore situato nella parte anteriore della pistola, contribuendo alla sua particolare estetica.\r\n\r\nCon un\'impugnatura ergonomicamente sagomata e un calcio pieghevole, la TMP è altamente adattabile a vari contesti operativi. Il selettore di fuoco offre modalità semiautomatica e automatica, garantendo una flessibilità tattica. Il mirino integrato contribuisce alla precisione, rendendo la TMP idonea per situazioni di combattimento ravvicinato.', 'La Steyr TMP ha suscitato interesse per la sua configurazione innovativa e la sua maneggevolezza. Utilizzata in contesti tattici e operazioni speciali, la sua leggerezza e compattezza la rendono ideale per situazioni ad alta mobilità. La TMP ha trovato impiego in vari ambiti, compresi reparti di polizia e forze di sicurezza, dove la sua versatilità è cruciale in spazi ristretti.\r\n\r\nLa presenza della TMP nel mercato civile è stata limitata, ma il suo design unico ha catturato l\'attenzione degli appassionati di armi da fuoco. Il suo ruolo nell\'evoluzione delle submachine gun moderna e l\'innovativo approccio al design la collocano come una delle armi da fuoco più distintive e avanzate nel suo genere.', NULL, 'Caratteristiche della Steyr TMP', 'Impatto e Utilizzo della Steyr TMP');


CREATE TABLE `grenades` (
  `ID` int(11) NOT NULL,
  `marca` text DEFAULT NULL,
  `modello` text DEFAULT NULL,
  `stato` text DEFAULT NULL,
  `titolo` text DEFAULT NULL,
  `maintext` text DEFAULT NULL,
  `secondarytext` text DEFAULT NULL,
  `summary` text DEFAULT NULL,
  `sub1` text DEFAULT NULL,
  `sub2` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;



INSERT INTO `grenades` (`ID`, `marca`, `modello`, `stato`, `titolo`, `maintext`, `secondarytext`, `summary`, `sub1`, `sub2`) VALUES
(1, NULL, 'M67', 'USA', 'Granata a Mano M67', 'La Granata a Mano M67 rappresenta un\'icona nella famiglia delle munizioni esplosive portatili. Progettata negli Stati Uniti durante la guerra del Vietnam, questa granata è rimasta in servizio per decenni grazie alla sua semplicità, affidabilità e efficacia. Il corpo esterno è composto da metallo con scanalature per migliorare la presa, mentre l\'innesco avviene attraverso una spoletta che consente il conteggio prima dell\'esplosione.\r\n\r\nL\'M67 è nota per la sua potenza distruttiva in un raggio limitato, con frammenti metallici che si disperdono nell\'area circostante dopo l\'esplosione. Il tempo di ritardo, controllato dalla spoletta, offre flessibilità operativa in vari scenari. La sua adozione estesa nel corso degli anni testimonia la sua versatilità e affidabilità in campo militare.', 'La M67 è stata impiegata in diversi conflitti e operazioni militari in tutto il mondo, mostrando la sua efficacia nella neutralizzazione di minacce nemiche e nella creazione di ostacoli difensivi. La sua presenza è predominante nelle forze armate degli Stati Uniti e di molti altri paesi alleati. La sua semplicità di utilizzo, combinata con l\'effetto devastante, ha contribuito a farne uno strumento cruciale per le forze militari e di sicurezza.\r\n\r\nLa Granata a Mano M67 ha anche suscitato discussioni su questioni etiche e umanitarie, in quanto il suo utilizzo può comportare danni significativi. Il suo design robusto e la sua funzionalità affidabile continuano a mantenere la M67 come un elemento chiave nel panorama delle munizioni esplosive, con l\'attenzione costante rivolta alle norme di impiego e alle implicazioni etiche.', NULL, 'Caratteristiche della Granata a Mano M67', 'Impatto e Utilizzo della Granata a Mano M67'),
(2, NULL, 'RGO', 'Russia', 'Granata a Mano RGO', 'La granata RGO, comunemente conosciuta come F1/RGO, è un dispositivo esplosivo portatile di origine russa. Progettata per l\'uso militare, questa granata è stata introdotta durante la Guerra Fredda e ha mantenuto la sua rilevanza nel corso degli anni. La sua forma è tipicamente sferica, con una superficie segmentata che facilita la frammentazione al momento dell\'esplosione.\r\n\r\nL\'RGO è alimentata da una carica esplosiva interna, e il suo principale meccanismo letale è rappresentato dai frammenti metallici generati dall\'esplosione. La gittata effettiva e l\'efficacia della granata RGO la rendono adatta per l\'uso in situazioni di combattimento ravvicinato o per il controllo delle folle. Il tempo di ritardo prima dell\'esplosione può essere regolato, consentendo una certa flessibilità tattica.', 'La granata RGO ha visto ampio impiego nelle forze armate russe e in altre nazioni che hanno adottato l\'armamento sovietico o russo. La sua capacità di generare frammenti a elevata velocità la rende efficace contro obiettivi in area aperta. La RGO è stata utilizzata in conflitti regionali e situazioni di combattimento, contribuendo alla sicurezza e alla difesa tattica delle forze militari.\r\n\r\nÈ importante sottolineare che, data la sua natura bellica, la granata RGO è soggetta a normative internazionali sul controllo delle armi, poiché il suo utilizzo deve avvenire nel rispetto delle leggi internazionali che regolano il conflitto armato e la sicurezza globale.', NULL, 'Caratteristiche della Granata a Mano RGO', 'Impatto e Utilizzo della Granata RGO'),
(3, '', 'L2 A2', 'Regno Unito', 'Granata a Mano L2A2', 'La L2 A2, comunemente nota come L2A2, rappresenta un\'importante evoluzione nel campo delle granate a frammentazione. Questo ordigno, originario del Regno Unito, è stato sviluppato per migliorare l\'efficacia e la sicurezza delle granate militari. La L2A2 utilizza un meccanismo di innesco avanzato e un involucro resistente per garantire una detonazione controllata e prevedibile.\r\n\r\nIl design ergonomico dell\'involucro offre una presa sicura e agevola il lancio preciso. La testa della granata è progettata per massimizzare l\'effetto di frammentazione, rendendola efficace in una varietà di scenari operativi. La L2A2 è nota anche per il suo sistema di sicurezza avanzato che impedisce l\'attivazione accidentale.', 'La L2A2 ha ottenuto una diffusa adozione nelle forze armate britanniche e in molte forze di sicurezza internazionali. La sua precisione e affidabilità la rendono una scelta ideale per l\'uso in situazioni tattiche e di combattimento. L\'effetto di frammentazione controllato aumenta l\'efficacia della granata in teatri operativi diversificati.\r\n\r\nOltre al suo impiego militare, la L2A2 è parte integrante delle risorse utilizzate in addestramenti e simulazioni, contribuendo alla formazione delle forze armate. La sua presenza è una testimonianza della costante ricerca di miglioramenti nelle tecnologie delle munizioni. La L2A2 rimane una componente essenziale dell\'arsenale militare, giocando un ruolo significativo nella sicurezza e nell\'efficacia operativa delle forze armate.', NULL, 'Caratteristiche della L2 A2', 'Impatto e Utilizzo della L2A2'),
(4, NULL, 'F1', 'Francia', 'Granata a Mano F1', 'La Granata F1 rappresenta un\'importante componente delle armi da lancio tattiche, sviluppata originariamente dalla Francia. Introdotta negli anni \'70, questa granata offre una combinazione di letalità e praticità. La sua forma distintiva, con il corpo affusolato e la testa a frammentazione, facilita il suo utilizzo e la sua efficacia in campo.\r\n\r\nLa Granata F1 è equipaggiata con un innesco a spoletta temporizzata, che consente un ritardo prima dell\'esplosione, massimizzando l\'impatto durante l\'uso tattico. La sua carica esplosiva è progettata per generare frammenti che aumentano l\'efficacia nell\'area circostante al momento dell\'esplosione. La sicura e intuitiva impugnatura ne semplifica la manipolazione.', 'La Granata F1 ha visto un ampio impiego nelle forze armate e nelle forze di polizia di diverse nazioni, evidenziando la sua versatilità in una varietà di contesti operativi. Utilizzata per neutralizzare minacce in punti chiusi o all\'aperto, la F1 ha dimostrato la sua efficacia in situazioni di combattimento ravvicinato. La sua adozione è il risultato di una progettazione attenta, che bilancia potenza distruttiva e sicurezza d\'uso.\r\n\r\nL\'utilizzo della Granata F1 va oltre il campo militare, trovando applicazioni anche nelle operazioni di sicurezza interna e nella gestione di situazioni di crisi. La sua presenza è un elemento essenziale nelle strategie di difesa e sicurezza, e la sua progettazione mirata riflette un impegno per la precisione e l\'efficacia nell\'arsenale delle forze dell\'ordine e militari.', NULL, 'Caratteristiche della Granata F1', 'Impatto e Utilizzo della Granata F1'),
(5, NULL, 'RGD-5', 'Russia', 'Granata a Mano RGD-5', 'La granata RGD-5 rappresenta un classico nell\'arsenale delle granate a frammentazione sovietiche, sviluppata durante la metà del XX secolo. Questo ordigno a mano è stato progettato per una vasta gamma di applicazioni tattiche e presenta un guscio in metallo, spesso rivestito di verde, con caratteristiche distintive come la spoletta di sicurezza sulla parte superiore.\r\n\r\nIl cuore della RGD-5 è costituito da una carica esplosiva ad alto potenziale, progettata per generare frammenti letali nell\'esplosione. La spoletta di sicurezza impedisce l\'attivazione accidentale durante la manipolazione. La RGD-5 è nota per la sua semplicità d\'uso, con una leva di sicurezza facilmente azionabile e un meccanismo di innesco rapido.', 'La RGD-5 è stata ampiamente utilizzata dalle forze armate sovietiche e dai loro alleati durante la Guerra Fredda e in vari conflitti regionali. La sua efficacia nel generare una zona di letale frammentazione ha contribuito al suo utilizzo in scenari di combattimento. La granata ha mantenuto la sua rilevanza anche dopo la dissoluzione dell\'Unione Sovietica, con diverse nazioni che continuano ad impiegarla nelle forze armate e nelle forze di sicurezza.\r\n\r\nLa sua adozione è stata influenzata dalla sua affidabilità, semplicità e dalla capacità di produrre un effetto devastante in un raggio circostante. Nonostante il suo carattere prevalentemente militare, la RGD-5 ha suscitato preoccupazioni in ambito civile per il suo utilizzo improprio e il contrabbando.', NULL, 'Caratteristiche della granata RGD-5', 'Impatto e Utilizzo della granata RGD-5');



CREATE TABLE `grenade_launcher` (
  `ID` int(11) NOT NULL,
  `marca` text DEFAULT NULL,
  `modello` text DEFAULT NULL,
  `stato` text DEFAULT NULL,
  `titolo` text DEFAULT NULL,
  `maintext` text DEFAULT NULL,
  `secondarytext` text DEFAULT NULL,
  `summary` text DEFAULT NULL,
  `sub1` text DEFAULT NULL,
  `sub2` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


INSERT INTO `grenade_launcher` (`ID`, `marca`, `modello`, `stato`, `titolo`, `maintext`, `secondarytext`, `summary`, `sub1`, `sub2`) VALUES
(1, '', 'M203', 'Stati Uniti', 'Lanciagranate M203', 'Il Lanciagranate M203, un\'innovativa aggiunta alle armi da fuoco, è un dispositivo a tamburo progettato per l\'attacco a granate su fucili d\'assalto standard. La sua origine risale agli anni \'60, ed è stato ampiamente utilizzato per potenziare la capacità di fuoco di vari fucili militari. Montato sotto la canna di un fucile, il M203 spara granate da 40mm, aggiungendo una dimensione esplosiva alla potenza di fuoco dell\'arma principale.\r\n\r\nL\'M203 è caratterizzato da un design compatto e leggero, facilitando la sua integrazione su diverse piattaforme. La canna può essere caricata con una varietà di granate, tra cui fumogene, illuminanti e granate anticarro. La sua interfaccia d\'uso semplice consente al tiratore di passare rapidamente dalla modalità di fuoco principale a quella del lanciagranate, estendendo la versatilità tattica dell\'arma.', 'Il Lanciagranate M203 ha rivoluzionato le capacità di fuoco delle forze armate, permettendo loro di affrontare efficacemente situazioni di combattimento in vari scenari. La sua utilità si estende dalla neutralizzazione di bunker e postazioni nemiche fino al supporto in operazioni di sgombero di ostacoli. La sua presenza è stata rilevante in conflitti recenti, evidenziando il ruolo chiave del M203 nel potenziare la potenza di fuoco delle truppe di terra.\r\n\r\nOltre al suo uso militare, il M203 è stato adottato anche da forze di sicurezza e reparti di polizia per situazioni tattiche specifiche. La sua flessibilità e la sua efficacia hanno reso il M203 un componente essenziale nella dotazione di molte forze armate, contribuendo a plasmare le strategie tattiche moderne.', NULL, 'Caratteristiche del Lanciagranate M203', 'Impatto e Utilizzo del Lanciagranate M203'),
(2, 'Heckler & Koch', 'AG36', 'Germania', 'Lanciagranate AG36', 'Il lanciagranate AG36, progettato dalla Heckler & Koch, è una componente versatile e potente integrata nei fucili d\'assalto moderni. Aggiungendo un livello di versatilità al repertorio delle armi da fuoco, l\'AG36 è noto per la sua capacità di sparare granate da 40mm. Questo accessorio, fissato sotto il calcio del fucile, è concepito per l\'utilizzo con fucili d\'assalto come il G36 della stessa casa produttrice.\r\n\r\nDotato di una canna corta e di un sistema di mira dedicato, l\'AG36 consente al tiratore di effettuare con precisione colpi esplosivi a distanza. Il design ergonomico facilita l\'integrazione con il fucile principale e il sistema di caricamento rapido agevola l\'efficienza in situazioni di combattimento. La selezione di granate varia da proiettili HE (ad alto esplosivo) a proiettili fumogeni o illuminanti, ampliando ulteriormente le opzioni operative.', 'L\'AG36 ha dimostrato la sua efficacia in situazioni tattiche e di supporto al fuoco, offrendo una soluzione versatile in campi di battaglia contemporanei. Le forze armate e le unità speciali che impiegano il fucile G36 con l\'AG36 apprezzano la sua flessibilità operativa, fornendo una risposta efficace contro bersagli diversificati. La capacità di modificare rapidamente il fuoco da proiettili standard a granate conferisce una notevole potenza di fuoco supplementare.\r\n\r\nL\'utilizzo dell\'AG36 si estende oltre il contesto militare, con l\'accessorio che ha trovato impiego anche in operazioni di sicurezza interna. La sua presenza in vari teatri operativi sottolinea la sua importanza nell\'ambito delle armi da fuoco, offrendo un vantaggio tattico significativo in un pacchetto compatto e facilmente integrabile.', NULL, 'Caratteristiche del Lanciagranate AG36', 'Impatto e Utilizzo del Lanciagranate AG36\r\n\r\n'),
(3, NULL, 'GP-30', 'Russia', 'Lanciagranate GP-30', 'Il lanciagranate GP-30, sviluppato in Unione Sovietica, è un componente essenziale per potenziare la capacità di fuoco delle fucili d\'assalto, particolarmente associato all\'AK-74. Introdotto negli anni \'80, il GP-30 è un lanciagranate a canna singola che spara granate da 40mm. Il design integrato e la costruzione robusta consentono una facile installazione sotto la canna del fucile d\'assalto principale.\r\n\r\nIl GP-30 è noto per la sua semplicità d\'uso e la precisione nei tiri a breve e media distanza. L\'arma può ospitare una varietà di munizioni, inclusi proiettili esplosivi, fumogeni e illuminanti. La sua integrazione con l\'AK-74 aggiunge una dimensione tattica significativa, conferendo alla squadra una maggiore versatilità in situazioni di combattimento.', 'Il GP-30 è diventato uno strumento cruciale per le forze armate e le unità di fanteria in molte nazioni, particolarmente nell\'Europa orientale. La sua adozione ha arricchito la capacità di fuoco delle squadre, fornendo loro una risposta efficace in scenari operativi diversificati. L\'utilizzo del GP-30 ha dimostrato di essere strategico in situazioni di combattimento urbano e in ambienti confinati.\r\n\r\nLa versatilità del lanciagranate GP-30 si estende anche alla sua applicazione nelle forze speciali e nelle unità di polizia. La sua presenza in molte aree di conflitto ha sottolineato il ruolo chiave che svolge nel potenziare la potenza di fuoco delle truppe impegnate sul campo. La sua affidabilità e semplicità d\'uso continuano a garantirgli un posto rilevante nella panoramica delle armi tattiche contemporanee.', NULL, 'Caratteristiche del Lanciagranate GP-30', 'Impatto e Utilizzo del Lanciagranate GP-30'),
(4, 'Heckler & Koch', 'HK69A1', 'Germania', NULL, 'Il lanciagranate HK69A1, prodotto dalla Heckler & Koch, è un\'arma ausiliaria versatile e efficace, progettata per fornire un supporto aggiuntivo alle forze armate. Questo lanciagranate monocolpo è stato sviluppato negli anni \'70 in Germania. Equipaggiato per sparare granate da 40mm, il lanciagranate HK69A1 è noto per la sua precisione e affidabilità.\r\n\r\nLa sua struttura compatta e leggera facilita il trasporto e l\'impiego tattico sul campo. La capacità di montaggio su varie piattaforme, come fucili d\'assalto, ne amplifica la versatilità. Il sistema di mira integrato, insieme alla canna rigata, contribuisce alla precisione di tiro, mentre il calcio pieghevole favorisce la praticità in situazioni operative.', 'L\'HK69A1 ha trovato impiego in numerose forze armate e reparti di polizia in tutto il mondo, fornendo una risposta efficace in situazioni in cui è richiesta una potenza di fuoco esplosiva a breve e media distanza. La sua presenza è stata particolarmente significativa nelle operazioni di controllo delle folle e nelle missioni di supporto tattico.\r\n\r\nLa flessibilità dell\'HK69A1 si estende anche all\'ambito civile, dove può essere utilizzato per applicazioni di difesa personale in contesti di sicurezza privata. Il lanciagranate HK69A1, grazie alla sua affidabilità e capacità di adattamento, ha contribuito a definire gli standard nel campo dei lanciagranate portatili, rappresentando una componente cruciale dell\'arsenale tattico moderno.', NULL, 'Caratteristiche del Lanciagranate HK69A1', 'Impatto e Utilizzo del Lanciagranate HK69A1'),
(5, 'Milkor South Africa', 'M32 MGL', 'Sudafrica', 'Lanciagranate M32 MGL', 'Il lanciagranate M32 MGL (Multiple Grenade Launcher), prodotto dalla Milkor South Africa, è un\'arma da supporto tattico di straordinaria potenza e versatilità. Introdotto nel mondo delle armi da fuoco negli anni \'80, questo lanciagranate è progettato per sparare granate da 40mm con una rapidità impressionante. La sua struttura cilindrica, nota anche come revolver a canne multiple, consente una rapida successione di colpi senza la necessità di ricaricare ogni singolo proiettile.\r\n\r\nIl M32 MGL è leggero e maneggevole nonostante la sua potenza distruttiva, con un design ergonomico che facilita il controllo dell\'arma durante l\'uso. La sua canna rotante, che può contenere diversi proiettili, permette al tiratore di adattarsi rapidamente a varie situazioni, dalla difesa contro veicoli corazzati all\'attacco contro gruppi di combattenti.', 'Il M32 MGL ha dimostrato la sua efficacia sul campo di battaglia, diventando un\'importante risorsa per forze militari e di sicurezza in tutto il mondo. La sua capacità di fornire fuoco di supporto rapido e concentrato lo rende ideale per operazioni di soppressione e per gestire situazioni tattiche complesse. Il lanciagranate M32 MGL è stato ampiamente utilizzato in missioni di combattimento e operazioni anti-terrorismo, dove la sua potenza distruttiva è un elemento chiave.\r\n\r\nOltre al suo utilizzo militare, il M32 MGL ha trovato applicazioni nel settore della sicurezza, come strumento di difesa in ambienti ad alto rischio. La sua presenza nell\'arsenale tattico dimostra la sua rilevanza nel panorama delle armi da fuoco specializzate, confermando il suo status di lanciagranate di grande impatto.', NULL, 'Caratteristiche del Lanciagranate M32 MGL', 'Impatto e Utilizzo del Lanciagranate M32 MGL');



CREATE TABLE `hand_guns` (
  `ID` int(11) NOT NULL,
  `marca` text DEFAULT NULL,
  `modello` text DEFAULT NULL,
  `stato` text DEFAULT NULL,
  `titolo` text DEFAULT NULL,
  `maintext` text DEFAULT NULL,
  `secondarytext` text DEFAULT NULL,
  `summary` text DEFAULT NULL,
  `sub1` text DEFAULT NULL,
  `sub2` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;



INSERT INTO `hand_guns` (`ID`, `marca`, `modello`, `stato`, `titolo`, `maintext`, `secondarytext`, `summary`, `sub1`, `sub2`) VALUES
(1, 'Beretta', 'M9', 'Italia/USA', 'Beretta M9', 'La Beretta M9, una delle pistole semiautomatiche più iconiche, è stata adottata dall\'esercito statunitense negli anni \'80. Prodotto dall\'azienda italiana Beretta, questo lato a lato spara il calibro 9x19mm Parabellum. La M9 è nota per il suo design robusto e la sua affidabilità, con una struttura in acciaio e impugnatura ergonomica.\r\n\r\nIl sistema di chiusura a corto rinculo e il caricatore ad alta capacità, solitamente da 15 colpi, contribuiscono alla funzionalità della M9. La presenza del selettore di sicurezza e decocker offre una maggiore sicurezza durante l\'uso. L\'arma è spesso dotata di mirini notturni per migliorare la precisione in condizioni di scarsa illuminazione.', 'La Beretta M9 è diventata una delle pistole più riconoscibili al mondo, utilizzata da numerose forze armate e forze dell\'ordine internazionali. La sua presenza è stata significativa in varie operazioni militari e di polizia. La durata e l\'affidabilità della M9 sono emerse come elementi chiave nella sua continua adozione, offrendo un\'arma di servizio affidabile e precisa.\r\n\r\nOltre all\'impiego militare e di polizia, la Beretta M9 è stata diffusamente utilizzata anche tra i civili, particolarmente negli Stati Uniti, dove versioni commerciali sono state apprezzate per la loro precisione e per il design ergonomico. La M9 ha contribuito a plasmare la percezione delle pistole semiautomatiche, consolidando la sua posizione come un\'icona nel mondo delle armi da fuoco.', NULL, 'Caratteristiche della Beretta M9', 'Impatto e Utilizzo della Beretta M9'),
(2, 'Glock', '17', 'Austria', 'Glock 17', 'La Glock 17, sviluppata dall\'azienda austriaca Glock GmbH negli anni \'80, è una delle pistole semiautomatiche più iconiche e diffuse al mondo. Alimentata dal calibro 9x19mm Parabellum, la Glock 17 è nota per il suo design innovativo, affidabilità e facilità d\'uso. Realizzata principalmente in polimero, questa pistola offre un equilibrio tra leggerezza e resistenza.\r\n\r\nLa Glock 17 presenta una capacità di caricatore standard di 17 colpi e una configurazione con percussore lanciato, che contribuisce alla sua affidabilità in varie condizioni. Il sistema di sicurezza incorporato nella grilletto e il basso profilo dell\'arma la rendono particolarmente adatta al porto nascosto. Il design senza attrezzi della Glock 17 permette una manutenzione semplice e rapida.', 'La Glock 17 ha rivoluzionato il mondo delle pistole semiautomatiche grazie al suo concetto di design senza fronzoli e alla sua affidabilità, guadagnandosi una vasta adozione nelle forze di polizia e nei mercati civili. La sua popolarità è dovuta alla combinazione di dimensioni compatte, capacità di fuoco elevata e scarsa manutenzione, rendendola una scelta comune tra i professionisti della sicurezza e gli appassionati di armi da fuoco.\r\n\r\nUtilizzata in tutto il mondo come arma da difesa personale e servizio, la Glock 17 ha influenzato la progettazione delle pistole moderne. La sua ergonomia, la sicurezza integrata e la capacità di adattamento la rendono una presenza costante nel panorama delle armi da fuoco, continuando a stabilire nuovi standard nel settore.', NULL, 'Caratteristiche della Glock 17', 'Impatto e Utilizzo della Glock 17'),
(3, 'Sig Sauer', 'P226', 'Svizzera', 'Sig Sauer P226', 'La Sig Sauer P226, progettata dalla rinomata casa svizzero-tedesca Sig Sauer, è una pistola semiautomatica che ha guadagnato una reputazione globale per la sua affidabilità e precisione. Alimentata dal calibro 9x19mm Parabellum, la P226 è stata originariamente sviluppata per le forze armate, ma ha rapidamente conquistato anche il mercato civile. Il suo design classico presenta una canna lunga e un carrello in acciaio inox per migliorare la resistenza e la durabilità.\r\n\r\nLa P226 è nota per la sua ergonomia, con impugnature intercambiabili per adattarsi alle preferenze dell\'utente. Il sistema di azione singola/doppia e il selettore di sicurezza contribuiscono alla versatilità dell\'arma. Dotata di mirini notturni e di un\'ottima precisione di tiro, la P226 è adatta sia a scopi militari che civili.', 'La P226 ha raggiunto un ruolo di spicco nelle forze di sicurezza di tutto il mondo, diventando una delle pistole preferite da polizia e militari. La sua affidabilità ha contribuito al suo utilizzo in contesti operativi e tattici. La popolarità della P226 si estende anche agli appassionati di armi, grazie alla sua presenza in competizioni di tiro sportivo e come arma per la difesa personale.\r\n\r\nLa Sig Sauer P226, con la sua combinazione di design ergonomico e prestazioni di alto livello, continua a essere un punto di riferimento nel mondo delle pistole semiautomatiche. Il suo impatto nella storia delle armi da fuoco è testimone della costante innovazione e dell\'impegno di Sig Sauer per produrre armi di qualità superiore.\r\n\r\n\r\n\r\n\r\n\r\n', NULL, 'Caratteristiche della Sig Sauer P226', 'Impatto e Utilizzo della Sig Sauer P226'),
(4, 'Heckler & Koch', 'USP', 'Germania', 'Heckler & Koch USP', 'La Heckler & Koch USP (Universal Self-loading Pistol) è una pistola semiautomatica di fama mondiale, sviluppata dalla casa tedesca Heckler & Koch. Introdotto negli anni \'90, l\'USP è noto per la sua versatilità, affidabilità e precisione. Disponibile in varie configurazioni e calibri, è stata progettata per adattarsi a una vasta gamma di esigenze.\r\n\r\nIl design ergonomico dell\'USP presenta impugnature intercambiabili per adattarsi alle dimensioni della mano dell\'utilizzatore, mentre il sistema di sicurezza avanzato garantisce una gestione sicura dell\'arma. L\'USP è disponibile in diversi calibri, dal 9mm al .45 ACP, offrendo opzioni per soddisfare le preferenze dell\'utilizzatore. La sua costruzione robusta e i dettagli tecnologici avanzati contribuiscono alla sua affidabilità in varie condizioni operative.', 'L\'USP di Heckler & Koch ha ottenuto un\'ampia adozione tra le forze dell\'ordine, le unità speciali e i civili grazie alla sua combinazione di prestazioni elevate e versatilità. Il design modulare e le caratteristiche avanzate lo rendono adatto a molteplici ruoli, tra cui difesa personale, tiro sportivo e applicazioni operative.\r\n\r\nLa presenza dell\'USP nella cultura delle armi da fuoco è sottolineata dalla sua popolarità globale e dalla sua utilizzazione in molteplici contesti. Concepita come una pistola universale per adattarsi a una vasta gamma di esigenze, la H&K USP continua a rappresentare un\'icona nell\'ambito delle pistole semiautomatiche, mantenendo la sua reputazione di affidabilità e prestazioni elevate nel tempo.', NULL, 'Caratteristiche della H&K USP', 'Impatto e Utilizzo della H&K USP'),
(5, 'CZ', '75', 'Repubblica Ceca', 'CZ 75', 'La CZ 75, prodotta dalla Česká Zbrojovka (CZ) in Repubblica Ceca, è una pistola semiautomatica che ha conquistato una reputazione globale per la sua affidabilità e precisione. Introdotta negli anni \'70, la CZ 75 utilizza il calibro 9x19mm e si distingue per il suo design all\'avanguardia a doppia azione. Il telaio in acciaio e il caricatore in posizione bassa conferiscono all\'arma un baricentro equilibrato.\r\n\r\nIl sistema di chiusura a corto rinculo contribuisce alla gestione del rinculo, garantendo una rapida riacquisizione del bersaglio. L\'impugnatura ergonomica, il cane ambidestro e la sicura a slitta caratterizzano il design distintivo della CZ 75. La possibilità di condurre il primo colpo in modalità doppia azione o azione singola offre flessibilità all\'utilizzatore.', 'La CZ 75 è diventata una delle pistole più diffuse e rispettate al mondo, utilizzata sia da civili che da forze di polizia e militari. La sua precisione e la solidità costruttiva ne fanno un\'arma di elezione per competizioni sportive e difesa personale. Le numerose varianti e il suo adattamento a diverse esigenze hanno catturato l\'attenzione degli appassionati di armi da fuoco.\r\n\r\nL\'eredità della CZ 75 continua a crescere, dimostrando la sua duratura rilevanza nel panorama delle pistole semiautomatiche. La sua combinazione di design classico, affidabilità e versatilità contribuisce al suo impatto significativo nel mercato delle armi da fuoco, sia a fini professionali che ricreativi.', NULL, 'Caratteristiche della CZ 75', 'Impatto e Utilizzo della CZ 75');



CREATE TABLE `machine_guns` (
  `ID` int(11) NOT NULL,
  `marca` text DEFAULT NULL,
  `modello` text DEFAULT NULL,
  `stato` text DEFAULT NULL,
  `titolo` text DEFAULT NULL,
  `maintext` text DEFAULT NULL,
  `secondarytext` text DEFAULT NULL,
  `summary` text DEFAULT NULL,
  `sub1` text DEFAULT NULL,
  `sub2` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;



INSERT INTO `machine_guns` (`ID`, `marca`, `modello`, `stato`, `titolo`, `maintext`, `secondarytext`, `summary`, `sub1`, `sub2`) VALUES
(1, 'M', '240', 'USA', 'Mitragliatrice M240', 'La M240, una mitragliatrice leggera progettata negli Stati Uniti, rappresenta un punto di riferimento nell\'arsenale delle armi leggere. Concepita originariamente dalla Fabbrica di Armi di Herstal belga, questa robusta arma fu successivamente adottata e prodotta su licenza negli Stati Uniti. Alimentata dalla munizione 7,62x51mm NATO, la M240 è una mitragliatrice a supporto di squadra, apprezzata per la sua potenza di fuoco e affidabilità.\r\n\r\nCaratterizzata da una canna intercambiabile e raffreddata ad aria, la M240 è nota per la sua versatilità e precisione sostenuta durante il fuoco prolungato. Il sistema di alimentazione a nastro contribuisce alla capacità di fuoco continuo, mentre il calcio regolabile assicura stabilità durante l\'impiego. Il selettore di fuoco offre modalità automatica e semiautomatica.', 'La M240 è un elemento chiave nelle forze armate statunitensi e di numerose altre nazioni, svolgendo un ruolo cruciale nelle operazioni di supporto di squadra e nelle situazioni di fuoco sostenuto. La sua affidabilità e capacità di soppressione del fuoco la rendono ideale per il sostegno di fanteria e unità di combattimento. La presenza della M240 è stata rilevante in conflitti internazionali e missioni di mantenimento della pace.\r\n\r\nOltre al suo utilizzo militare, la M240 è stata adottata anche dalle forze dell\'ordine e in contesti di sicurezza nazionale. La sua robustezza e precisione la rendono un\'arma apprezzata anche in scenari civili, ad esempio nella difesa di aree sensibili o in operazioni di sicurezza privata. La M240 rappresenta un esempio di eccellenza nella progettazione delle mitragliatrici leggere, con un impatto profondo nel panorama delle armi da fuoco.', NULL, 'Caratteristiche della M240', 'Impatto e Utilizzo della M240'),
(2, 'MG', '3', 'Germania', 'MG 3', 'La MG3, una delle mitragliatrici di supporto più iconiche, è stata sviluppata dalla tedesca Rheinmetall nel corso degli anni \'50, basandosi sulla precedente MG 42 della Seconda Guerra Mondiale. Questa mitragliatrice adotta un calibro potente, il 7,62x51mm NATO, offrendo una potenza di fuoco significativa. Il design distintivo comprende un sistema di raffreddamento ad aria, caratteristico della sua progenitrice, e un elevato tasso di fuoco che la rende efficace in situazioni di supporto di fuoco.\r\n\r\nLa MG3 è solitamente montata su treppiede o su veicoli, dimostrando la sua versatilità in svariate applicazioni. Il caricatore a nastro la rende adatta a un fuoco continuo e prolungato. Il meccanismo di raffreddamento, sebbene classico, è noto per la sua affidabilità in condizioni di combattimento impegnative.', 'La MG3 ha avuto un impatto duraturo nel panorama delle armi leggere, essendo stata ampiamente utilizzata dalle forze armate di numerose nazioni. La sua presenza è stata significativa durante la Guerra Fredda e in conflitti successivi, dove la sua potenza di fuoco è stata sfruttata in ruoli difensivi e di supporto. La sua affidabilità in condizioni avverse e la maneggevolezza ne fanno una scelta preferita per le operazioni di supporto.\r\n\r\nOltre all\'uso militare, la MG3 è stata anche integrata in veicoli militari e imbarcazioni, contribuendo alla sua diffusione in varie forze armate. La sua eredità storica e la robustezza del suo design la rendono un\'arma durevole e rispettata nel panorama delle mitragliatrici di supporto.', NULL, 'Caratteristiche della MG3', 'Impatto e Utilizzo della MG3'),
(3, 'PK', 'M', 'Russia', 'PK M', 'La PKM è una mitragliatrice leggera sviluppata in Unione Sovietica negli anni \'60 e ancora in servizio in molte nazioni. Prodotto dalla Kalashnikov Concern, questo robusto fucile utilizza il calibro 7,62x54mmR, garantendo una potenza di fuoco considerevole. La sua struttura è basata su un design a canna corta e alimentazione tramite nastri di munizioni, con un supporto bipiede per una maggiore stabilità durante il tiro.\r\n\r\nLa PKM è nota per la sua affidabilità in condizioni avverse e il suo sistema di raffreddamento a liquido consente un tiro sostenuto senza perdita di precisione. Il calcio pieghevole consente una maggiore portabilità, rendendo questa mitragliatrice adatta sia per l\'uso stazionario che per le operazioni in movimento.', 'La PKM è stata ampiamente adottata in tutto il mondo e ha giocato un ruolo significativo in conflitti militari e operazioni di mantenimento della pace. La sua versatilità la rende ideale per ruoli di supporto, contribuendo alla superiorità di fuoco delle unità di fanteria. La presenza della PKM è stata rilevante anche in contesti di difesa nazionale e nelle mani di forze di sicurezza.\r\n\r\nOltre al suo impiego militare, la PKM è stata oggetto di interesse per i collezionisti di armi da fuoco e appassionati di storia militare. Il suo design classico e la sua affidabilità hanno contribuito a consolidarne la reputazione come una delle mitragliatrici leggere più iconiche nel panorama mondiale delle armi da fuoco.', NULL, 'Caratteristiche della PK M', 'Impatto e Utilizzo della PKM'),
(4, 'FN', 'MAG', 'Belgio', 'FN MAG', 'La FN MAG, progettata dall\'azienda belga Fabrique Nationale Herstal, è una mitragliatrice leggera che ha fatto la sua comparsa negli anni \'50. Conosciuta anche come M240 nelle forze armate degli Stati Uniti, questa arma adotta un design robusto e affidabile, impiegando il calibro 7,62x51mm NATO. La configurazione aperta e la canna sostituibile contribuiscono alla sua versatilità e affidabilità in condizioni operative.\r\n\r\nIl sistema a nastro della FN MAG consente l\'alimentazione continua di munizioni, rendendola adatta per il supporto di fuoco in varie situazioni. Il sistema di raffreddamento a doppio manicotto mantiene l\'arma efficiente durante il fuoco sostenuto. Il calcio ripiegabile e il bipiede migliorano la stabilità e la maneggevolezza.', 'La FN MAG ha avuto un impatto significativo nelle forze armate di tutto il mondo, diventando una delle mitragliatrici leggere più utilizzate. La sua presenza è stata rilevante in conflitti globali, grazie alla sua potenza di fuoco e alla capacità di soppressione. La sua adozione anche in varianti come la M240B negli Stati Uniti attesta la sua affidabilità.\r\n\r\nImpiegata in ruoli diversificati, dalla difesa delle trincee al supporto di fuoco mobile, la FN MAG ha dimostrato la sua versatilità sul campo di battaglia. Oltre all\'uso militare, la FN MAG è stata installata su veicoli e elicotteri, contribuendo alla sua ubiquità nelle operazioni militari complesse. La sua durata e il suo ruolo di supporto di fuoco continuano a consolidare la FN MAG come una delle mitragliatrici più influenti nella storia delle armi da fuoco.', NULL, 'Caratteristiche della FN MAG', 'Impatto e Utilizzo della FN MAG'),
(5, 'IWI', 'Negev', 'Israele', 'IWI Negev', 'La IWI Negev è una mitragliatrice leggera progettata dall\'Israeli Weapons Industries (IWI) in Israele. Introdotta nei primi anni 2000, questa arma è stata concepita per offrire una combinazione di mobilità e potenza di fuoco. La Negev utilizza il proiettile 5,56x45mm o 7,62x51mm NATO, fornendo una flessibilità in termini di munizionamento.\r\n\r\nCaratterizzata da un design robusto e dall\'utilizzo di materiali avanzati, la Negev ha un calcio telescopico regolabile e una canna intercambiabile per gestire il riscaldamento durante il fuoco sostenuto. Il sistema di raffreddamento è efficace, garantendo la continuità del fuoco senza surriscaldamenti eccessivi. La Negev è spesso equipaggiata con un mirino ottico e un sistema di puntamento avanzato.', 'La IWI Negev è stata adottata dalle Forze di Difesa Israeliane (IDF) e da altre forze armate in tutto il mondo, grazie alla sua affidabilità e capacità di sopportare un fuoco prolungato. L\'arma è utilizzata in vari contesti operativi, dalle missioni di pattugliamento alla difesa di obiettivi strategici. La sua versatilità è evidente anche nelle varianti destinate al mercato civile, dove la Negev ha attratto l\'interesse degli appassionati di armi da fuoco.\r\n\r\nConcepita per offrire una soluzione equilibrata tra potenza di fuoco e manovrabilità, la IWI Negev continua a svolgere un ruolo significativo nel panorama delle armi leggere contemporanee, evidenziando la continua innovazione nel settore delle armi da fuoco.', NULL, 'Caratteristiche della IWI Negev', 'Impatto e Utilizzo della IWI Negev');



CREATE TABLE `shotgun` (
  `ID` int(11) NOT NULL,
  `marca` text DEFAULT NULL,
  `modello` text DEFAULT NULL,
  `stato` text DEFAULT NULL,
  `titolo` text DEFAULT NULL,
  `maintext` text DEFAULT NULL,
  `secondarytext` text DEFAULT NULL,
  `summary` text DEFAULT NULL,
  `sub1` text DEFAULT NULL,
  `sub2` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `shotgun` (`ID`, `marca`, `modello`, `stato`, `titolo`, `maintext`, `secondarytext`, `summary`, `sub1`, `sub2`) VALUES
(1, 'Remington', '870', 'USA', 'Remington 870', 'La Remington 870, un classico nel mondo delle armi da fuoco, è una pump-action shotgun statunitense che ha mantenuto una presenza iconica per decenni. Introdotta negli anni \'50, questa fucile a pompa è diventata una delle scelte preferite per cacciatori, forze dell\'ordine e appassionati di armi da fuoco. La 870 è disponibile in varie configurazioni, ma la versione standard presenta un design tradizionale con calcio e pompa in legno.\r\n\r\nLa versatilità della Remington 870 si manifesta nella sua capacità di sparare cartucce da caccia, munizioni tattiche e munizioni non letali. La semplicità del sistema a pompa la rende affidabile e facile da usare. Il calcio ergonomico offre un\'impugnatura comoda, mentre il selettore di sicurezza e il mirino regolabile contribuiscono all\'esperienza di tiro.', 'La Remington 870 ha lasciato un\'impronta indelebile nel panorama delle armi da fuoco, divenendo una delle fucili a pompa più popolari al mondo. Utilizzata ampiamente per la caccia, la difesa personale e in molteplici scenari operativi, la 870 è stata adottata da numerose forze dell\'ordine grazie alla sua affidabilità e al suo design robusto.\r\n\r\nLa sua configurazione modulare permette agli utenti di personalizzarla secondo le proprie esigenze, rendendola un\'arma versatile. La Remington 870 è anche apprezzata dagli appassionati di armi da fuoco per la sua tradizione e per la disponibilità di varianti specializzate. In definitiva, la sua duratura presenza e la sua capacità di adattamento la rendono un\'icona nella categoria delle fucili a pompa.', NULL, 'Caratteristiche della Remington 870', 'Impatto e Utilizzo della Remington 870'),
(2, 'Mossberg', '500', 'USA', 'Mossberg 500', 'La Mossberg 500 è una fucile a pompa prodotta dalla O.F. Mossberg & Sons, un\'azienda statunitense con una lunga tradizione nella fabbricazione di armi da fuoco. Questo fucile a canna liscia è versatile e ampiamente utilizzato per attività come la caccia, il tiro sportivo e la difesa personale. Disponibile in numerose varianti, la Mossberg 500 è nota per la sua affidabilità e la robustezza della sua costruzione.\r\n\r\nIl fucile presenta una configurazione a pompa, il che significa che l\'utente deve manualmente azionare la pompa per espellere il bossolo sparato e inserire una nuova cartuccia. Questo design semplice ma efficace contribuisce alla sua popolarità. La Mossberg 500 è disponibile con canne di lunghezze diverse e può ospitare diversi tipi di munizioni, rendendola adatta a una vasta gamma di utilizzi.', 'La Mossberg 500 ha avuto un impatto notevole nel settore delle armi da fuoco grazie alla sua affidabilità e alla sua versatilità. È spesso scelta per la caccia, la difesa personale e l\'uso ricreativo, offrendo un\'ampia gamma di configurazioni per soddisfare le esigenze specifiche degli utenti. La sua facilità di manutenzione e la vasta disponibilità di accessori e parti di ricambio ne fanno una scelta popolare tra gli appassionati di armi da fuoco.\r\n\r\nOltre al suo impiego pratico, la Mossberg 500 ha ottenuto una notevole presenza anche nel mercato civile, dove è spesso considerata un\'opzione affidabile per chi cerca una soluzione di difesa domestica. La sua longevità e la sua reputazione consolidata la rendono un elemento riconoscibile nel panorama delle armi da fuoco negli Stati Uniti e oltre.', NULL, 'Caratteristiche della Mossberg 500', 'Impatto e Utilizzo della Mossberg 500'),
(3, 'Benelli', 'M4', 'Italia', 'Benelli M4', 'La Benelli M4, prodotta dall\'azienda italiana Benelli Armi, è un fucile semiautomatico a pompa adottato in ambito militare e civile. Introdotta negli anni \'90, l\'M4 è noto per la sua robustezza, affidabilità e flessibilità d\'uso. Sparando cartucce da 12 calibri, questo fucile ha una configurazione a gas che consente il fuoco rapido e la gestione efficace del rinculo.\r\n\r\nIl design ergonomico della M4 include un calcio telescopico regolabile e un\'impugnatura anteriore per migliorare la stabilità e la maneggevolezza. La canna corta e filettata consente l\'installazione di dispositivi di soppressione del suono o di accessori tattici. Il selettore di fuoco permette di alternare tra la modalità semiautomatica e quella a colpo singolo.', 'La Benelli M4 ha ottenuto un riconoscimento globale come fucile versatile utilizzato in contesti militari, forze dell\'ordine e difesa personale. La sua affidabilità in situazioni operative critiche, la precisione e la capacità di adattarsi a diversi carichi di munizioni contribuiscono alla sua popolarità. L\'M4 è stato adottato da varie forze armate, inclusa l\'US Marine Corps, evidenziando la sua qualità e la sua affidabilità.\r\n\r\nOltre al suo impiego militare e di sicurezza, la Benelli M4 è ampiamente utilizzata nella cultura civile, specialmente tra gli appassionati di tiro sportivo e di difesa personale. La sua reputazione di resistenza e versatilità continua a consolidarsi, rendendo la M4 una scelta di riferimento per chi cerca un fucile semiautomatico robusto e affidabile.\r\n\r\n\r\n\r\n\r\n\r\n', NULL, 'Caratteristiche della Benelli M4', 'Impatto e Utilizzo della Benelli M4'),
(4, 'Izhmash', 'Saiga-12', 'Russia', 'Izhmash Saiga-12', 'La Izhmash Saiga-12, prodotta in Russia, è una shotgun semiautomatica derivata dalla serie di fucili d\'assalto Kalashnikov. Quest\'arma, alimentata dai tradizionali caricatori a tamburo o caricatori a scatola, spara il calibro 12, offrendo una potenza di fuoco considerevole. Il design robusto e la costruzione affidabile sono distintivi della tradizione delle armi russe.\r\n\r\nCaratterizzata da un calcio pieghevole o telescopico, la Saiga-12 può essere facilmente adattata alle preferenze dell\'utente. La canna liscia la rende versatile per un\'ampia gamma di munizioni, permettendo un utilizzo efficace sia in situazioni di difesa personale che nella caccia. La sua configurazione semiautomatica consente un tiro rapido e preciso.\r\n', 'La Izhmash Saiga-12 ha guadagnato popolarità per la sua capacità di combattere in situazioni di combattimento ravvicinato, rendendola una scelta preferita tra forze di sicurezza e appassionati di armi da fuoco. La sua versatilità è particolarmente evidente in contesti operativi urbani o in situazioni tattiche che richiedono una risposta rapida.\r\n\r\nOltre al suo utilizzo tattico, la Saiga-12 è stata impiegata anche nella caccia, sfruttando la potenza del calibro 12. La presenza di varianti civili ha ampliato la sua diffusione tra i civili, suscitando interesse tra gli appassionati di armi. Il design robusto e la reputazione di affidabilità consolidano la Saiga-12 come una delle shotgun più riconoscibili e versatili nel panorama delle armi da fuoco.', NULL, 'Caratteristiche della Izhmash Saiga-12', 'Impatto e Utilizzo della Izhmash Saiga-12'),
(5, 'Winchester', '1300', 'USA', 'Winchester 1300', 'La Winchester 1300 è una fucile a pompa americana prodotta dalla Winchester Repeating Arms Company. Introdotta negli anni \'70, si distingue per la sua affidabilità e versatilità. Disponibile in diverse varianti, la 1300 spara cartucce da 12 o 20 calibri e può essere utilizzata per una varietà di scopi, tra cui caccia e difesa personale.\r\n\r\nIl design ergonomico della 1300 offre una presa confortevole, mentre il meccanismo a pompa consente una rapida e affidabile alimentazione delle cartucce. Il calcio può essere regolato per adattarsi alle preferenze dell\'utente, e l\'arma spesso include caratteristiche come mirini regolabili e tacche per migliorare la precisione.', 'La Winchester 1300 ha guadagnato popolarità tra cacciatori e tiratori sportivi per la sua robustezza e facilità d\'uso. La sua versatilità la rende adatta sia per la caccia di piccola e media taglia che per il tiro al bersaglio. La presenza della 1300 si estende anche al campo della difesa personale, dove la sua capacità di sparare munizioni potenti a pompa offre un\'opzione affidabile per la sicurezza domestica.\r\n\r\nCon una lunga storia di produzione e una reputazione di solidità, la Winchester 1300 ha stabilito un solido seguito tra gli appassionati di armi da fuoco. La sua presenza in molte armerie e il suo utilizzo diffuso sottolineano il suo impatto duraturo nel mondo delle armi da fuoco, continuando a essere una scelta apprezzata per vari scopi.', NULL, 'Caratteristiche della Winchester 1300', 'Impatto e Utilizzo della Winchester 1300');




CREATE TABLE `sniper_rifles` (
  `ID` int(11) NOT NULL,
  `marca` text DEFAULT NULL,
  `modello` text DEFAULT NULL,
  `stato` text DEFAULT NULL,
  `titolo` text DEFAULT NULL,
  `maintext` text DEFAULT NULL,
  `secondarytext` text DEFAULT NULL,
  `summary` text DEFAULT NULL,
  `sub1` text DEFAULT NULL,
  `sub2` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;



INSERT INTO `sniper_rifles` (`ID`, `marca`, `modello`, `stato`, `titolo`, `maintext`, `secondarytext`, `summary`, `sub1`, `sub2`) VALUES
(1, 'AWM', 'L115A3', 'Regno Unito', 'AWM L115A3', 'L\'AWM (Arctic Warfare Magnum) L115A3, prodotto dalla Precision Marksman della britannica Accuracy International, rappresenta un fucile di precisione di alto livello noto per la sua letale precisione e capacità di colpire bersagli a lunga distanza. Quest\'arma è alimentata dalla munizione .300 Winchester Magnum, fornendo una combinazione ideale di potenza e precisione.\r\n\r\nIl design ergonomico e modulare dell\'AWM L115A3 si distingue per la sua canna lunga e filettata per l\'installazione di dispositivi di soppressione del suono o altri accessori. Il calcio regolabile consente la personalizzazione per adattarsi alle preferenze dell\'utente, mentre il sistema di mira avanzato contribuisce alla sua efficacia nelle situazioni di tiro di precisione.', 'L\'AWM L115A3 è stato ampiamente adottato dalle forze armate, compresi reparti di tiratori scelti e unità speciali, grazie alle sue prestazioni eccezionali in operazioni di osservazione e colpo unico. La sua gittata estrema e la precisione balistica lo rendono ideale per situazioni di tiro a lunga distanza. L\'utilizzo dell\'AWM L115A3 è stato rilevante anche in ambienti operativi specifici, come nelle missioni di cecchino militare.\r\n\r\nOltre all\'impiego militare, l\'AWM L115A3 ha trovato applicazioni nel tiro sportivo di precisione e nelle competizioni. Il suo status come fucile di precisione di élite sottolinea il suo impatto nel mondo delle armi da fuoco, confermando la sua posizione come un\'arma di riferimento nella categoria dei fucili di precisione.', NULL, 'Caratteristiche dell\'AWM L115A3', 'Impatto e Utilizzo dell\'AWM L115A3'),
(2, 'Sako', 'TRG', 'Finlandia', 'Sako TRG', 'La Sako TRG, prodotta dall\'azienda finlandese Sako, rappresenta un\'eccellenza nell\'ambito dei fucili di precisione e tiro a lunga distanza. Disponibile in diverse varianti, questo fucile è noto per la sua precisione estrema e la versatilità. Impiega una vasta gamma di calibri, tra cui il 308 Winchester e il 338 Lapua Magnum, adattandosi alle esigenze specifiche degli utenti.\r\n\r\nIl design della Sako TRG è ergonomico, con un calcio regolabile che consente una personalizzazione ottimale per il tiratore. La canna pesante, dotata di filettatura per l\'installazione di freni di bocca o silenziatori, garantisce una stabilità superiore durante il tiro. La presenza di un grilletto regolabile contribuisce alla precisione del tiro.', 'La Sako TRG ha stabilito uno standard elevato nel mondo dei fucili di precisione ed è stata adottata da militari, forze dell\'ordine e tiratori sportivi in tutto il mondo. La sua precisione straordinaria e la capacità di mantenere elevate prestazioni anche a lunghe distanze ne fanno uno strumento ideale per operazioni di tiro di precisione e cecchino.\r\n\r\nOltre al suo utilizzo militare e tattico, la Sako TRG è apprezzata dai tiratori civili impegnati in competizioni di tiro a lunga distanza e attività sportive. La sua reputazione di affidabilità e precisione avanzata ha contribuito a posizionarla come un\'icona nel settore dei fucili di precisione, rappresentando l\'eccellenza finlandese nel mondo delle armi da fuoco.', NULL, 'Caratteristiche della Sako TRG', 'Impatto e Utilizzo della Sako TRG'),
(3, 'Remington', '700', 'USA', 'Remington 700', 'La Remington 700, introdotta nel 1962 dalla Remington Arms Company, è un fucile a otturatore girevole-scorrevole che ha ottenuto una reputazione iconica nel mondo dei tiratori sportivi e dei cacciatori. Disponibile in diverse varianti, il modello è spesso associato ai fucili da precisione grazie alle sue eccezionali capacità balistiche. La Remington 700 è spesso chambered in calibri come il .308 Winchester, garantendo una potenza di fuoco adeguata.\r\n\r\nLa configurazione del fucile presenta un\'azione di otturatore solido che contribuisce alla sua precisione, mentre il calcio, disponibile in legno o materiale sintetico, offre comfort e adattabilità. Il grilletto regolabile contribuisce alla precisione del tiro, rendendo la Remington 700 una scelta preferita per il tiro a lunga distanza. La presenza di una canna filettata consente l\'installazione di accessori come freni di bocca o silenziatori.', 'La Remington 700 è stata ampiamente utilizzata nelle competizioni di tiro a lunga distanza e nel mondo della caccia, grazie alla sua affidabilità e precisione. Molte forze di polizia e unità militari hanno adottato varianti del modello per le loro esigenze di tiro di precisione. La versatilità del fucile è evidente nella sua applicazione anche nell\'ambito civile, dove è apprezzato tra gli appassionati di tiro sportivo e caccia.\r\n\r\nL\'eredità della Remington 700 è consolidata nella sua lunga storia di servizio e nell\'impatto che ha avuto su diverse comunità di tiratori. La sua combinazione di qualità costruttiva, precisione e adattabilità continua a renderla una scelta rinomata nel mondo delle armi da fuoco.', NULL, 'Caratteristiche della Remington 700', 'Impatto e Utilizzo della Remington 700'),
(4, 'Dragunov', 'SVD', 'Russia', 'Dragunov SVD', 'Il fucile da precisione Dragunov SVD, di origine sovietica, è un\'icona nella categoria dei fucili da cecchino sviluppato nei primi anni \'60. Progettato da Evgeniy Dragunov, questo fucile utilizza il calibro 7,62x54mmR, noto per la sua potenza e precisione. La sua configurazione semi-automatica offre una cadenza di tiro controllata, mentre il sistema a gas a corto rinculo garantisce una maggiore stabilità in tiro.\r\n\r\nIl Dragunov SVD presenta un design elegante e una canna pesante che favorisce la precisione a lunga gittata. L\'impugnatura ergonomica e il calcio regolabile consentono un adattamento personalizzato, mentre il sistema di mira ottico integrato contribuisce alla precisione delle riprese. La capacità del caricatore, tipicamente da 10 colpi, sottolinea il suo ruolo come fucile da cecchino dedicato.', 'Il Dragunov SVD è stato ampiamente utilizzato dalle forze armate sovietiche e successivamente da numerose nazioni in tutto il mondo. La sua efficacia a lunga distanza e la potenza del calibro lo rendono ideale per missioni di cecchino e operazioni di supporto al fuoco. L\'arma ha partecipato a conflitti globali, guadagnando una reputazione per la sua precisione e affidabilità.\r\n\r\nOltre all\'impiego militare, il Dragunov SVD è stato adottato anche da civili e collezionisti, evidenziando il suo impatto culturale e storico. Il suo design distintivo e la sua storia lo collocano tra i fucili da cecchino più riconoscibili e rispettati del XX secolo.', NULL, 'Caratteristiche del Dragunov SVD', 'Impatto e Utilizzo del Dragunov SVD'),
(5, 'Barrett', 'M82', 'USA', 'Barrett M82', 'La Barrett M82, conosciuta anche come \"Light Fifty,\" è un fucile anti-materiale sviluppato negli Stati Uniti dalla Barrett Firearms Manufacturing. Introdotta negli anni \'80, è una delle armi più potenti nella categoria dei fucili a lunga gittata. Questo fucile a otturatore girevole scorrevole è calibrato per la cartuccia .50 BMG, conferendogli un\'impressionante potenza di fuoco.\r\n\r\nLa lunga canna del M82 e la sua precisione lo rendono ideale per ruoli anti-materiale e per colpire bersagli a lunga distanza. Il design bullpup offre una configurazione compatta nonostante il calibro massiccio, mentre il calcio regolabile e l\'impugnatura ergonomica contribuiscono alla stabilità del tiro. La capacità di montare accessori come mirini telescopici aumenta ulteriormente la sua efficacia.', 'La Barrett M82 è stata ampiamente adottata dalle forze armate in tutto il mondo per le sue capacità anti-materiale e per la sua efficacia contro veicoli corazzati leggeri. Spesso utilizzata in ruoli di cecchino anti-materiale, la M82 è stata parte integrante in teatri di guerra moderni. La sua presenza è notevole anche nelle forze di sicurezza per applicazioni specializzate.\r\n\r\nOltre al suo ruolo militare, la Barrett M82 è ricercata tra gli appassionati di armi da fuoco per la sua potenza e precisione. Il suo status di fucile iconico e la capacità di influenzare il campo delle armi da fuoco a lunga gittata sottolineano il suo impatto duraturo nella storia delle armi da fuoco.', NULL, 'Caratteristiche della Barrett M82', 'Impatto e Utilizzo della Barrett M82');


CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `user_name` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;



INSERT INTO `users` (`id`, `user_name`, `password`, `name`) VALUES
(1, 'admin', '1234', 'Kevin'),
(2, 'porro', '1234', 'Matteo'),
(3, 'sappia', '1234', 'Fulvio');





CREATE TABLE `white_weapons` (
  `ID` int(11) NOT NULL,
  `marca` text DEFAULT NULL,
  `modello` text DEFAULT NULL,
  `stato` text DEFAULT NULL,
  `titolo` text DEFAULT NULL,
  `maintext` text DEFAULT NULL,
  `secondarytext` text DEFAULT NULL,
  `summary` text DEFAULT NULL,
  `sub1` text DEFAULT NULL,
  `sub2` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;



INSERT INTO `white_weapons` (`ID`, `marca`, `modello`, `stato`, `titolo`, `maintext`, `secondarytext`, `summary`, `sub1`, `sub2`) VALUES
(1, 'Ka-Bar', '1370', 'USA', 'Ka-Bar 1370', 'Il Ka-Bar 1370 rappresenta un classico nell\'ambito dei coltelli tattici, prodotto dalla rinomata Ka-Bar Knives. Caratterizzato da una lama robusta in acciaio inossidabile di alta qualità, il Ka-Bar 1370 offre un\'ottima combinazione di durabilità e precisione. Il suo design intramontabile include una lama a clip point per una maggiore versatilità nelle attività all\'aperto.\r\n\r\nLa struttura del manico, realizzata in materiali resistenti e ergonomici, fornisce una presa sicura e confortevole. La guardia in metallo protegge efficacemente le mani durante l\'uso, garantendo sicurezza nelle situazioni tattiche. Il Ka-Bar 1370 è noto anche per la sua resistenza alla corrosione, rendendolo adatto a una vasta gamma di ambienti e condizioni atmosferiche.', 'Il Ka-Bar 1370 ha guadagnato una reputazione consolidata tra militari, appassionati di outdoor e professionisti di sicurezza grazie alla sua affidabilità e al suo design senza tempo. È stato impiegato in varie situazioni operative, dal campo di battaglia agli ambienti wilderness, dimostrando la sua versatilità nell\'affrontare compiti diversificati come taglio, scavo e perforazione.\r\n\r\nOltre al suo utilizzo tattico-militare, il Ka-Bar 1370 è un\'opzione apprezzata anche tra gli amanti del bushcraft e degli sport all\'aperto. La sua robustezza e precisione nella lavorazione lo rendono un compagno fidato in molte avventure. La lunga storia e la qualità costruttiva del Ka-Bar 1370 consolidano la sua posizione come uno dei coltelli tattici più riconosciuti e affidabili sul mercato.', NULL, 'Caratteristiche del Ka-Bar 1370', 'Impatto e Utilizzo del Ka-Bar 1370'),
(2, 'W.E.', 'Fairbairn-Sykes', 'Regno Unito', 'W.E. Fairbairn-Sykes', 'Il W.E. Fairbairn-Sykes, noto anche come Fairbairn-Sykes Commando Dagger, è un pugnale da combattimento con una storia ricca e venerabile. Originariamente sviluppato durante la Seconda Guerra Mondiale per le forze speciali britanniche, questo pugnale è diventato un\'icona nel mondo delle armi da mischia. La lama da 7 pollici presenta una forma affilata e aguzza, progettata per penetrare efficacemente attraverso indumenti e tessuti.\r\n\r\nIl design del Fairbairn-Sykes riflette l\'approccio pragmatico degli esperti di combattimento William E. Fairbairn e Eric A. Sykes, che ne concepirono la forma ergonomica e il bilanciamento ideale per un utilizzo veloce e preciso. L\'impugnatura in metallo e il design sottile consentono una presa salda, mentre la guardia a croce protegge la mano dell\'utilizzatore durante l\'uso.', 'Il Fairbairn-Sykes ha avuto un impatto significativo nelle operazioni di combattimento a distanza ravvicinata durante la Seconda Guerra Mondiale. Utilizzato principalmente dai Commando britannici, il pugnale è diventato un simbolo di forza e determinazione nelle forze speciali. La sua efficacia nel corpo a corpo lo ha reso uno strumento essenziale per gli operatori speciali impegnati in missioni di infiltrazione e sabotaggio.\r\n\r\nOltre al suo impiego militare, il Fairbairn-Sykes ha mantenuto la sua rilevanza come coltello da collezione e oggetto d\'interesse per gli appassionati di storia militare. Il suo design senza tempo e la sua connessione con le unità speciali conferiscono al pugnale una posizione di prestigio nella storia delle armi bianche.', NULL, 'Caratteristiche del W.E. Fairbairn-Sykes', 'Impatto e Utilizzo del W.E. Fairbairn-Sykes'),
(3, 'Ontario', 'Mark 3 Navy Knife', 'USA', 'Ontario Mark 3 Navy Knife', 'L\'Ontario Mark 3 Navy Knife rappresenta un\'icona nell\'ambito dei coltelli da combattimento, prodotto dall\'azienda statunitense Ontario Knife Company. Progettato originariamente per l\'U.S. Navy durante la Seconda Guerra Mondiale, questo coltello si distingue per la sua robustezza e affidabilità. La lama, realizzata in acciaio al carbonio 1095, è caratterizzata da una forma a punta di lancia e una finitura nera anti-riflesso.\r\n\r\nL\'impugnatura ergonomica, spesso realizzata in cuoio o kraton, offre una presa sicura anche in condizioni avverse. Il passaggio completo attraverso l\'impugnatura contribuisce alla solidità e alla durabilità complessiva. L\'Ontario Mark 3 Navy Knife è spesso accompagnato da una robusta fodera in pelle o nylon, conferendogli una completa praticità tattica.', 'L\'Ontario Mark 3 Navy Knife ha lasciato un\'impronta duratura nella storia dei coltelli militari, trovando impiego non solo nella Marina degli Stati Uniti ma anche in molte altre forze armate e reparti speciali. La sua lama robusta e la praticità nell\'uso tattico lo rendono ideale per situazioni di combattimento e sopravvivenza. Il design intramontabile di questo coltello ha ispirato molte altre varianti e imitazioni nel mondo degli accessori tattici.\r\n\r\nOltre al suo utilizzo militare, l\'Ontario Mark 3 Navy Knife è apprezzato tra gli appassionati di coltelli per le sue qualità artigianali e la sua funzionalità. La sua presenza continua a definire gli standard nei coltelli militari, incarnando la resistenza e l\'affidabilità richieste in situazioni tattiche impegnative.', NULL, 'Caratteristiche dell\'Ontario Mark 3 Navy Knife', 'Impatto e Utilizzo dell\'Ontario Mark 3 Navy Knife'),
(4, 'Wakizashi', 'Tanto', 'Giappone', 'Wakizashi Tanto', 'La Wakizashi è una spada giapponese corta, caratterizzata da una lama appuntita e affilata, lunga generalmente tra i 30 e i 60 centimetri. Tradizionalmente utilizzata come arma secondaria dai samurai, la Wakizashi è parte integrante della cultura delle arti marziali giapponesi. La sua lama, forgiata con precisione artigianale, è spesso decorata e presenta un\'architettura affascinante.\r\n\r\nIl manico, noto come tsuka, è progettato per offrire una presa sicura e confortevole. L\'impugnatura può essere avvolta in seta o pelle, arricchendo l\'estetica complessiva dell\'arma. La guardia, o tsuba, è spesso decorata con motivi simbolici o artistici, contribuendo all\'unicità della Wakizashi. Il fodero, chiamato saya, solitamente realizzato in legno o seta, svolge un ruolo protettivo per la lama.', 'La Wakizashi, parte integrante della cultura giapponese, è stata storicamente indossata dai samurai come complemento al più lungo katana. Utilizzata come arma di difesa personale e simbolo di status, la Wakizashi ha una lunga tradizione nelle arti marziali giapponesi. La sua versatilità la rendeva efficace in spazi ristretti e situazioni di combattimento ravvicinato.\r\n\r\nOggi, la Wakizashi continua a suscitare interesse come oggetto di collezionismo e nelle pratiche delle arti marziali tradizionali. La sua rilevanza storica, insieme al suo design elegante e funzionale, la rende un simbolo duraturo della maestria artigianale giapponese e della ricca eredità delle armi tradizionali.', NULL, 'Caratteristiche della Wakizashi', 'Impatto e Utilizzo della Wakizashi'),
(5, 'Boker', 'Applegate-Fairbairn', 'Germania', 'Boker Applegate-Fairbairn', 'Il coltello da combattimento Boker Applegate-Fairbairn rappresenta un\'eccellenza nel mondo dei coltelli tattici, frutto della collaborazione tra Boker, rinomata azienda tedesca, e i leggendari coltellinai William E. Fairbairn e Rex Applegate. Questo coltello, progettato per applicazioni tattiche e militari, offre un equilibrio superiore tra resistenza e maneggevolezza.\r\n\r\nLa lama in acciaio inossidabile di alta qualità è sagomata con una punta affilata e presenta un filo continuo per garantire prestazioni durature. La presa ergonomica e antiscivolo del manico, realizzato in materiali resistenti, offre una salda aderenza durante l\'uso. Il design classico del Boker Applegate-Fairbairn include un sistema di bloccaggio affidabile e una lama efficiente sia in situazioni tattiche che quotidiane.', 'Il Boker Applegate-Fairbairn è stato adottato in vari contesti professionali e tattici, diventando una scelta preferita tra personale militare, forze dell\'ordine e appassionati di coltelli. La sua reputazione si basa sulla sua funzionalità, facilità d\'uso e durabilità. La versatilità del coltello è evidente nelle sue applicazioni, che spaziano dalla difesa personale al taglio di materiali resistenti.\r\n\r\nOltre al suo utilizzo tattico, il Boker Applegate-Fairbairn ha conquistato l\'attenzione degli appassionati di coltelli per la sua estetica classica e il design intramontabile. La collaborazione tra Boker e i leggendari coltellinai ha creato un coltello iconico, rimanendo un punto di riferimento nel mondo delle lame tattiche e dimostrando l\'importanza di un design affidabile e ben pensato.', NULL, 'Caratteristiche del Boker Applegate-Fairbairn', 'Impatto e Utilizzo del Boker Applegate-Fairbairn');


ALTER TABLE `assault_rifles`
  ADD PRIMARY KEY (`ID`);


ALTER TABLE `assault_smg`
  ADD PRIMARY KEY (`ID`);


ALTER TABLE `grenades`
  ADD PRIMARY KEY (`ID`);


ALTER TABLE `grenade_launcher`
  ADD PRIMARY KEY (`ID`);


ALTER TABLE `hand_guns`
  ADD PRIMARY KEY (`ID`);


ALTER TABLE `machine_guns`
  ADD PRIMARY KEY (`ID`);


ALTER TABLE `shotgun`
  ADD PRIMARY KEY (`ID`);



ALTER TABLE `sniper_rifles`
  ADD PRIMARY KEY (`ID`);


ALTER TABLE `white_weapons`
  ADD PRIMARY KEY (`ID`);
COMMIT;


